apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-sn8b
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0042-tenant/tkrw-pr712-0075-0042-app/devfile-sample-sn8b@sha256:2de6d81d08cfc5cc83825b6b05120889cd9b8d04f71991287020de261624e651
        name: my-nodejs
        resources: {}
status: {}
